### ISSUE TITLE
How does it compare to another library

### ISSUE THREAD

**Issue by nikivdev** [ddPn08/decorock#1]
I found this library but I previously used https://github.com/solidjs/solid-styled-components

And curious how this library compares. API seems very similar. Is the difference only in the API?

Thanks.

**Comment by ddPn08** [comment]
This is a library I modified for myself based on the mentioned library. The theme's reactivity etc. have been fixed.

**Comment by nikivdev** [comment]
Makes sense. :)

I would maybe PR that library too as its under official solid github handle and will have more reach.
